### ISSUE TITLE
Match history sorting

### ISSUE THREAD

**Issue by benjamindoe** [Ben-Bromley/office-pong#2]
Match history should probably show in descending order

**Comment by Ben-Bromley** [comment]
Had to add timestamps to matches after 45 matches had already been submitted. So the first 45 won't sort correctly unless I go through and change all of the dates in the database (which might be worth it I haven't decided yet). All new matches should sort in descending order (most recent first)

May need some testing with a local db if it doesn't work

timestamps added to models - https://github.com/Ben-Bromley/office-pong/commit/9961ab466c32b7d10dcac62c8ccaad0af3e09579
Match sorting added - https://github.com/Ben-Bromley/office-pong/commit/7bcd68716f87d908acdbf15754d2af83a8f9a8b5
