### ISSUE TITLE
Login page flickers if already auth

### ISSUE THREAD

**Issue by benjamindoe** [Ben-Bromley/office-pong#5]
If you are already authenticated, you see the Google login button. After a few seconds it goes away and shows you the dashboard button

**Comment by Ben-Bromley** [comment]
getting session server side might be best here, having the session ready before the page is loaded should remove the flicker

https://next-auth.js.org/configuration/nextjs#unstable_getserversession

**Comment by Ben-Bromley** [comment]
using server session to eliminate flicker: https://github.com/Ben-Bromley/office-pong/commit/1236da544cebeb119b1185d02dc48f8efa52891d
