### ISSUE TITLE
Skeleton page

### ISSUE THREAD

**Issue by benjamindoe** [Ben-Bromley/office-pong#6]
Initial load of the dashboard shows no data and empty cards. Could do with a skeleton page for initial load

**Comment by Ben-Bromley** [comment]
Skeleton content has been added!

A number other fixes have been added since, but this is the main commit for that addition: https://github.com/Ben-Bromley/office-pong/commit/c4b53c18fcb85ee27fa71b82ffa82ac8e572404c
