### ISSUE TITLE
Full page reload after submitting a match

### ISSUE THREAD

**Issue by benjamindoe** [Ben-Bromley/office-pong#7]
The whole page is reloading after a match is submitted. Only the components that need updating should update.

**Comment by Ben-Bromley** [comment]
full reload was done as an easy fix to get the latest data showing. I need to look into having the data refetched properly instead. Probably something in TRPC / react-query that can help here

**Comment by Ben-Bromley** [comment]
https://github.com/Ben-Bromley/office-pong/pull/11
